# Generated by Django 6.0.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
